from django.contrib import admin
from .models import Profile, Application, Country, School, Student, Exchange, Interest, Message, Review, Document, Event, Announcement, Gallery, GalleryImage, FAQ, Poll, Vote, Scholarship, Resource, News, BlogPost, Feedback, Program, StudentStory, PartnerUniversity, CareerOpportunity, CulturalImmersionProgram, LanguageLearningExperience

admin.site.register(Profile)
admin.site.register(Application)
admin.site.register(Country)
admin.site.register(School)
admin.site.register(Student)
admin.site.register(Exchange)
admin.site.register(Interest)
admin.site.register(Message)
admin.site.register(Review)
admin.site.register(Document)
admin.site.register(Event)
admin.site.register(Announcement)
admin.site.register(Gallery)
admin.site.register(GalleryImage)
admin.site.register(FAQ)
admin.site.register(Poll)
admin.site.register(Vote)
admin.site.register(Scholarship)
admin.site.register(Resource)
admin.site.register(News)
admin.site.register(BlogPost)
admin.site.register(Feedback)
admin.site.register(Program)
admin.site.register(StudentStory)
admin.site.register(PartnerUniversity)
admin.site.register(CareerOpportunity)
admin.site.register(CulturalImmersionProgram)
admin.site.register(LanguageLearningExperience)
